service: multiple-external

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  stage: dev
  region: eu-west-2

custom:
  webpackIncludeModules: true # enable auto including modules

functions:
  hello:
    handler: hello.hello
    events:
      - http:
          method: GET
          path: hello
          integration: lambda
  longLink:
    handler: longLink.longLink
    events:
      - http:
          method: POST
          path: longlink
